minion/server/models.py
"""
    `minion-ci` is a minimalist, decentralized, flexible Continuous Integration Server for hackers.

    This module contains the models to persist CI job data.

    :copyright: (c) by Timo Furrer
    :license: MIT, see LICENSE for details
"""

import os
import datetime
from flask_mongoengine import MongoEngine

db = MongoEngine()


class Result(db.EmbeddedDocument):  # pylint: disable=no-init,too-few-public-methods
    """Document to store a job test result."""
    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    status = db.StringField(default="submitted")
    error_msg = db.StringField()
    logs = db.StringField(default="")


class Job(db.Document):  # pylint: disable=no-init,too-few-public-methods
    """Document to store a single minion-ci job."""
    meta = {
                'ordering': ['-created_at']
    }

    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    repository_url = db.StringField(required=True)
    commit_hash = db.StringField()
    branch = db.StringField()
    attributes = db.DictField()
    result = db.EmbeddedDocumentField(Result)

    config_file = "minion.yml"


def mongo_to_dict(obj):
    """Turn a mongoengine object into a jsonible python object."""

    return_data = []
    if isinstance(obj, db.Document):
        return_data.append(("id", str(obj.id)))

    for field_name in obj._fields:
        data = obj._data[field_name]

        if isinstance(obj._fields[field_name], db.DateTimeField):
            return_data.append((field_name, str(data.isoformat())))
        elif isinstance(obj._fields[field_name], db.StringField):
            return_data.append((field_name, str(data)))
        elif isinstance(obj._fields[field_name], db.BooleanField):
            return_data.append((field_name, bool(data)))
        elif isinstance(obj._fields[field_name], db.FloatField):
            return_data.append((field_name, float(data)))
        elif isinstance(obj._fields[field_name], db.IntField):
            return_data.append((field_name, int(data)))
        elif isinstance(obj._fields[field_name], (db.ListField, db.DictField)):
            return_data.append((field_name, data))
        elif isinstance(obj._fields[field_name], db.EmbeddedDocumentField):
            return_data.append((field_name, mongo_to_dict(data)))
        elif isinstance(obj._fields[field_name], db.ObjectIdField):
            return_data.append((field_name, str(data)))

    return dict(return_data)

minion/server/__init__.py
"""
    `minion-ci` is a minimalist, decentralized, flexible Continuous Integration Server for hackers.

    This package contains the minion-ci server.

    :copyright: (c) by Timo Furrer
    :license: MIT, see LICENSE for details
"""

minion/server/app.py
"""
    `minion-ci` is a minimalist, decentralized, flexible Continuous Integration Server for hackers.

    This module contains the server code for `minion-ci`.

    :copyright: (c) by Timo Furrer
    :license: MIT, see LICENSE for details
"""

import re
import click
import yaml
from flask import Flask
from jinja2 import evalcontextfilter, Markup, escape

from .config import DefaultConfig
from .routes import api
from .models import db
from .core import workers


def parse_config(path):
    """Parse minion-ci server configuration file."""
    with open(path) as config_file:
        return yaml.load(config_file)


@evalcontextfilter
def nl2br(eval_ctx, value):
    _paragraph_re = re.compile(r'(?:\r\n|\r|\n){2,}')
    result = u'\n\n'.join(u'<p>%s</p>' % p.replace('\n', '<br>\n') \
        for p in _paragraph_re.split(escape(value)))
    if eval_ctx.autoescape:
        result = Markup(result)
    return result


def create_app(name):
    """Create flask app"""
    app = Flask(__name__)
    app.register_blueprint(api)
    app.config.from_object(DefaultConfig)

    try:
        app.config.update(parse_config(app.config["DEFAULT_CONFIGURATION_FILE"]))
    except FileNotFoundError:
        pass

    # add required filters
    app.jinja_env.filters["nl2br"] = nl2br

    # initialize mongodb engine for use in flask
    db.init_app(app)

    # initilize worker pool and job queue
    workers.init_app(app)

    return app

minion/server/routes.py
"""
    `minion-ci` is a minimalist, decentralized, flexible Continuous Integration Server for hackers.

    This module contains the routes for the minion-ci API.

    :copyright: (c) by Timo Furrer
    :license: MIT, see LICENSE for details
"""

import re
import mongoengine
from flask import Blueprint, request, jsonify, render_template

from .models import Job, mongo_to_dict
from .core import workers, stop_server, ensure_mongo
from ..errors import MinionMongoError

api = Blueprint("api", __name__)

@ensure_mongo
def get_jobs_page(page=1, page_size=10):
    """Returns all jobs from the given page."""
    return Job.objects.paginate(page=page, per_page=page_size)


@api.route("/", methods=["GET"])
def index():
    """Serve index HTML."""
    page = int(request.args.get("page", 1))
    return render_template("index.html", jobs=get_jobs_page(page=page))

@api.route("/status", methods=["GET"])
def get_status():
    """Get status of the minion server."""
    status = {
        "queue": {
            "size": workers.queue.qsize()
        },
        "jobs": {

        }
    }
    return jsonify(status)


@api.route("/jobs", methods=["GET"])
@ensure_mongo
def get_jobs():
    """Serve list of jobs."""
    page = int(request.args.get("page", 1))
    page_size = int(request.args.get("pageSize", 10))
    return jsonify({"jobs": [mongo_to_dict(j) for j in get_jobs_page(page, page_size).items]})



@api.route("/jobs/<job_id>", methods=["GET"])
@ensure_mongo
def get_job(job_id):
    """Serve information of specific job."""
    job = Job.objects.get(id=job_id)
    return jsonify({"job": mongo_to_dict(job)})


@api.route("/jobs", methods=["POST"])
@ensure_mongo
def create_job():
    """Create a new job"""
    data = request.json
    job = {
        "repository_url": data.pop("repo_url", None),
        "commit_hash": data.pop("commit_hash", None),
        "branch": data.pop("branch", None),
        "keep_data": data.pop("keep_data", False),
        "attributes": data
    }
    workers.queue.put(job)
    return jsonify({"status": True})


@api.route("/jobs", methods=["DELETE"])
@ensure_mongo
def delete_jobs():
    """Delete all jobs."""
    Job.drop_collection()
    return jsonify({"status": True})



@api.route("/jobs/<job_id>", methods=["DELETE"])
@ensure_mongo
def delete_job(job_id):
    """Delete a specific job."""
    try:
        job = Job.objects.get(id=job_id)
    except mongoengine.errors.ValidationError:
        return jsonify({"status": False, "msg": "No such job id found: {0}".format(job_id)})
    else:
        job.delete()
        return jsonify({"status": True})


@api.route('/stop', methods=['POST'])
@ensure_mongo
def stop():
    stop_server()
    return 'Stopping server'

@api.errorhandler(MinionMongoError)
def mongodb_not_runnings(error):
    """Throw error if we can't connect to mongodb"""
    print("Can't connect or reconnect to mongodb")
    return jsonify({'data': "Could not parse data. Ensure that MongoDB is running"}), 500

minion/server/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>minion CI</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="//cdn.jsdelivr.net/font-hack/2.019/css/hack-extended.min.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/minion.css') }}">
    </head>
    <body>
        <div class="container">
            <img class="logo" src="{{ url_for('static', filename='images/minion.png') }}">
            <header>
                <h1>minion CI</h1>
            </header>
            <ul class="jobs">
                {% if jobs.items %}
                    {% for job in jobs.items %}
                        <li class="job">
                            <span class="time">{{ job.created_at }}</span>
                            <span class="repository_url">{{ job.repository_url }}</span>
                            <span class="revision">{{ job.commit_hash[:7] }}</span>
                            <div class="result_status">
                            {% if job.result.status == "succeded" %}
                            <span class="success">&#10003;&nbsp;SUCCESS</span>
                            {% elif job.result.status == "running" %}
                            <span class="running">&#8635;&nbsp;RUNNING</span>
                            {% else %}
                            <span class="failure">&#10008;&nbsp;FAILURE</span>
                            {% endif %}
                            </div>
                            <div class="result">
                                {% if job.result.status == "failure" %}
                                <strong class="failure_red">{{ job.result.error_msg }}:</strong> <br><br>
                                {% endif %}
                                {{ job.result.logs | nl2br }}
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                <li class="job">
                    There are no jobs in the database!
                </li>
                {% endif %}
            </ul>
            <footer>
                <nav class="my-pagination">
                    Page:
                    {%- for page in jobs.iter_pages() %}
                        {% if page %}
                            {% if page != jobs.page %}
                                <a href="{{ url_for('api.index', page=page) }}">{{ page }}</a>
                            {% else %}
                                <strong>{{ page }}</strong>
                            {% endif %}
                        {% else %}
                            <span class=ellipsis>…</span>
                        {% endif %}
                    {%- endfor %}
                </nav>
                <div class="copyright">
                    <strong>minion-ci</strong>, published under MIT. A <a href="https://github.com/timofurrer" target="_blank">Timo Furrer</a> Project.
                </div>
            </footer>
        </div>


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

        <script>
            $(document).ready(function() {
                $(".job").click(function(event) {
                    $(this).find("div.result").toggle();
                });
            });
        </script>
    </body>
</html>